apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-database-assetinv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: efs-asset
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /tmp
    server: 172.31.24.59

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: assetinv-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: efs-asset
  