apiVersion: v1
kind: Service
metadata:
  name: assetinv3-service
spec:
  type: ClusterIP
  selector:
    app: assetinv2-ingress
    tier: aplikasi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: assetinv3-deployment
  labels:
    app: assetinv2-ingress
    tier: aplikasi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assetinv2-ingress
      tier: aplikasi
  template:
    metadata:
      labels:
        app: assetinv2-ingress
        tier: aplikasi
    spec:
      containers:
      - name: assetinv2-ingress
        image: sudarsonohadisaputra/asset-inv:saas-v30
        ports:
        - containerPort: 80

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: nginx-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - assetinv2.solubis.net
      secretName: assetinv2-tls
  rules:
    - host: assetinv2.solubis.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: assetinv3-service
                port:
                  number: 80
