name: Dockerize php web apps
on: push
jobs:
  build-container:
    name: Build Docker Container Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag asset-inv:saas-v27
      - name: publish to Dockerhub
        uses: docker/build-push-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: sudarsonohadisaputra/asset-inv
          tags: saas-v27
